### ISSUE TITLE
[PSPE] Missing animation when breaking blocks

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#17]
When breaking blocks, the blocks disappear without an animation on PE.

This is on an iPad. Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by 7kasper** [comment]
Fixed.

**Comment by magicus** [comment]
If by "fix" you are referring to 5a4786c2edd727b7c3f38830b62004ddcd6283cd, unfortunately it did not work. :-( At least on iPad, I still get no breaking animations.

**Comment by 7kasper** [comment]
Weird, I got em on both my phone and my dads tablet and w10...

**Comment by magicus** [comment]
Any idea on how I can help debug this? Can I put a breakpoint/debug print somewhere to see if the proper data seems to be sent to the client?

**Comment by 7kasper** [comment]
Can you check for me if you can see the break animations of other players?

**Comment by magicus** [comment]
You're probably onto something. :-) Yes, I can see the animations when a PC player breaks the blocks. (I currently do not have a second PE player to test with)

**Comment by 7kasper** [comment]
Try compiling again and breaking a few blocks.

**Comment by 7kasper** [comment]
Can yoi test it on windows 10 or another os / decice? It seems weird but theres a very slight chance its os related. Otherwise check if it happens if you are not alone. It might only send block packets when someone is near (in all my tests someone was near so thats why I think that)

**Comment by magicus** [comment]
I have a W10 installation I can try it on, perhaps tomorrow.

When I have tested right now I have had my PE and my PC characters in roughly the same spot. So I have not been alone. And the PE player sees the animations from the PC player (which certainly must be nearby! :-)), but not from their own blocks.

**Comment by 7kasper** [comment]
And? Your minecraft is up to date right? I find it very weird that I see the cracks on PE 🤔

**Comment by magicus** [comment]
Yes, my minecraft is up to date.

I have not been able to test the W10 client; I have a dual boot machine and have not been able to leave my Linux session due to too many open work windows. :-&

**Comment by 7kasper** [comment]
When you are close to a pc client though, do you see blocks being broken on botg clients by both clients?

**Comment by magicus** [comment]
No. 

I'll try to explain:
I placed my PE player shoulder to shoulder with my PC player.
I place a block with PC player. Both players see it appear. I break the block with PC player. Both player see it break, and both see the animation.
Now I place a block with PE player. Both players see it appear. I break the block with PE player. Both player see it break, but only PC player see animation. PE player just sees it vanish instantly.

**Comment by magicus** [comment]
And this is still present as of today.

**Comment by 7kasper** [comment]
Poop

**Comment by magicus** [comment]
I'll try to get some time tomorrow to test with my W10 installation. (I'd wake up my wife if I booted that computer right now)
