### ISSUE TITLE
[PSPE] Teleporting player to different yaw value doesn't work for pe clients

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupportPocketStuff#52]
Teleporting player to different yaw value doesn't work for pe clients.
This can be reproduced by having a player positioned with yaw 0 then trying to teleport them to the same location with yaw 90. The server recognizes that the direction the player is facing has been updated, but the client doesn't recognize that.
This is really messing up a mini-game on my server right now.
[https://youtu.be/IJTQvSVBAUU](url)

**Comment by 7kasper** [comment]
Fixed

**Comment by Speentie8081** [comment]
Issue is still not fixed. Please fix this as soon as you can, thank you.

**Comment by 7kasper** [comment]
Reporter specified only 'frozen' clients have this.
